# proto_library rules implicitly depend on @com_google_protobuf//:protoc,
# which is the proto-compiler.
# This statement defines the @com_google_protobuf repo.
http_archive(
    name = "com_google_protobuf",
    urls = ["https://github.com/google/protobuf/archive/b4b0e304be5a68de3d0ee1af9b286f958750f5e4.zip"],
    strip_prefix = "protobuf-b4b0e304be5a68de3d0ee1af9b286f958750f5e4",
    sha256 = "ff771a662fb6bd4d3cc209bcccedef3e93980a49f71df1e987f6afa3bcdcba3a",
)

# cc_proto_library rules implicitly depend on @com_google_protobuf_cc//:cc_toolchain,
# which is the C++ proto runtime (base classes and common utilities).
http_archive(
    name = "com_google_protobuf_cc",
    urls = ["https://github.com/google/protobuf/archive/b4b0e304be5a68de3d0ee1af9b286f958750f5e4.zip"],
    strip_prefix = "protobuf-b4b0e304be5a68de3d0ee1af9b286f958750f5e4",
    sha256 = "ff771a662fb6bd4d3cc209bcccedef3e93980a49f71df1e987f6afa3bcdcba3a",
)

# java_proto_library rules implicitly depend on @com_google_protobuf_java//:java_toolchain,
# which is the Java proto runtime (base classes and common utilities).
http_archive(
    name = "com_google_protobuf_java",
    urls = ["https://github.com/google/protobuf/archive/b4b0e304be5a68de3d0ee1af9b286f958750f5e4.zip"],
    strip_prefix = "protobuf-b4b0e304be5a68de3d0ee1af9b286f958750f5e4",
    sha256 = "ff771a662fb6bd4d3cc209bcccedef3e93980a49f71df1e987f6afa3bcdcba3a",
)

# java_lite_proto_library rules implicitly depend on @com_google_protobuf_javalite//:javalite_toolchain,
# which is the JavaLite proto runtime (base classes and common utilities).
http_archive(
    name = "com_google_protobuf_javalite",
    urls = ["https://github.com/google/protobuf/archive/82809aaebf24fca3c2d5611149c78a3625bd3b70.zip"],
    strip_prefix = "protobuf-82809aaebf24fca3c2d5611149c78a3625bd3b70",
    sha256 = "75105f312cefd8aa5e0bdf29279dc8ef0a6f862362b321d35b1ed5c08ce2ecfb",
)

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    sha1 = "cce0823396aa693798f8882e64213b1772032b09",
)

maven_jar(
    name = "com_google_inject_guice",
    artifact = "com.google.inject:guice:4.1.0",
    sha1 = "eeb69005da379a10071aa4948c48d89250febb07",
)

maven_jar(
    name = "org_java_websocket",
    artifact = "org.java-websocket:Java-WebSocket:1.3.4",
    sha1 = "55cd7147462307abb6f83f73b291e4ae53906dfa",
)

maven_jar(
    name = "javax_inject",
    artifact = "javax.inject:javax.inject:1",
    sha1 = "6975da39a7040257bd51d21a231b76c915872d38",
)

maven_jar(
    name = "aopalliance",
    artifact = "aopalliance:aopalliance:1.0",
    sha1 = "0235ba8b489512805ac13a8f9ea77a1ca5ebe3e8",
)

maven_jar(
    name = "protobuf_java_util",
    artifact = "com.google.protobuf:protobuf-java-util:3.3.1",
    sha1 = "35d048270e0b2f29e7e4a45daf21d46d1b121a24",
)

maven_jar(
    name = "protobuf_java",
    artifact = "com.google.protobuf:protobuf-java:3.3.1",
    sha1 = "e8964a2667e55d11a4505b329a4c34247663920b",
)

maven_jar(
    name = "gson",
    artifact = "com.google.code.gson:gson:2.8.1",
    sha1 = "02a8e0aa38a2e21cb39e2f5a7d6704cbdc941da0",
)

maven_jar(
    name = "ta4j",
    artifact = "eu.verdelhan:ta4j:0.8",
    sha1 = "9d8b153a160dae074654b15fc05d9afc47a5133b",
)

maven_jar(
    name = "okhttp3",
    artifact = "com.squareup.okhttp3:okhttp:3.8.1",
    sha1 = "4d060ca3190df0eda4dc13415532a12e15ca5f11",
)

maven_jar(
    name = "okio",
    artifact = "com.squareup.okio:okio:1.13.0",
    sha1 = "a9283170b7305c8d92d25aff02a6ab7e45d06cbe",
)

maven_jar(
    name = "joda_time",
    artifact = "joda-time:joda-time:2.9.9",
    sha1 = "f7b520c458572890807d143670c9b24f4de90897",
)
